@baseUrl = http://47.96.98.60:8080/ZZB/
@token = 13154564531


### 
POST {{baseUrl}}login/applogin
content-type : application/x-www-form-urlencoded
equipmentId : test
Authorization: {{token}}

{
    "username" : "18818131887",
    "password" : "123456"
}


